SOURCE_MAP = {
    "sbc_kn_m2": "FOOTING!E8",
    "design_load_kn": "FOOTING!E9",
    "mux_knm": "FOOTING!E10",
    "muy_knm": "FOOTING!E11",
    "column_width_mm": "FOOTING!E12",
    "column_depth_mm": "FOOTING!E13",
    "fck_mpa": "FOOTING!E14",
    "fy_mpa": "FOOTING!E15",
    "ru_max": "FOOTING!E16 (reconciled: derived from fck/fy)",
    "self_weight_kn": "FOOTING!E18",
    "total_load_kn": "FOOTING!E19",
    "required_area_m2": "FOOTING!E22",
    "required_length_mm": "FOOTING!E26",
    "required_width_mm": "FOOTING!E28",
    "footing_length_mm": "FOOTING!E30",
    "footing_width_mm": "FOOTING!E32 (reconciled for rectangular column)",
    "provided_area_m2": "FOOTING!E34",
    "base_pressure_factored": "FOOTING!E38",
    "pmax_x": "FOOTING!E43",
    "pmin_x": "FOOTING!E44",
    "pmax_x_working": "FOOTING!E48",
    "pmin_x_working": "FOOTING!E49 (reconciled live dependency)",
    "pmax_y": "FOOTING!E55",
    "pmin_y": "FOOTING!E56",
    "pmax_y_working": "FOOTING!E60",
    "pmin_y_working": "FOOTING!E61 (reconciled live dependency)",
    "projection_x_mm": "FOOTING!E67",
    "projection_y_mm": "FOOTING!E70",
    "moment_x_knm": "FOOTING!E79",
    "moment_y_knm": "FOOTING!E85",
    "required_eff_depth_x_mm": "FOOTING!E98 / E117 (relabelled)",
    "required_eff_depth_y_mm": "FOOTING!E101 / E119 (relabelled)",
    "bar_dia_mm": "FOOTING!E108 / E181",
    "cover_mm": "FOOTING!E110",
    "footing_depth_mm": "FOOTING!E122",
    "effective_depth_x_mm": "FOOTING!E124",
    "effective_depth_y_mm": "FOOTING!E126",
    "punching_capacity_kn": "FOOTING!E161",
    "punching_demand_kn": "FOOTING!E163 (reconciled)",
    "ast_x_req_mm2": "FOOTING!E169",
    "ast_y_req_mm2": "FOOTING!E171",
    "ast_x_min_mm2": "FOOTING!E173 (method-selectable)",
    "ast_y_min_mm2": "FOOTING!E175 (method-selectable)",
    "ast_x_to_provide_mm2": "FOOTING!E178 (reconciled axis reference)",
    "ast_y_to_provide_mm2": "FOOTING!E179 (reconciled axis reference)",
    "bars_x": "FOOTING!E182",
    "bars_y": "FOOTING!E186",
    "spacing_x_mm": "FOOTING!E183 (reconciled c/c spacing)",
    "spacing_y_mm": "FOOTING!E187 (reconciled c/c spacing)",
    "ld_required_mm": "FOOTING!E195 (reconciled bond stress)",
    "ld_available_mm": "FOOTING!E196",
    "one_way_y_capacity_kn": "FOOTING!E210",
    "one_way_y_demand_kn": "FOOTING!E212 (reconciled pressure axis)",
    "one_way_x_capacity_kn": "FOOTING!E230",
    "one_way_x_demand_kn": "FOOTING!E232 (reconciled pressure axis)",
    "column_bearing_demand_mpa": "FOOTING!E236 (reconciled: no second 1.5 factor)",
    "bearing_enhancement": "FOOTING!E242:E245 (reconciled cap = 2.0)",
}
